name: uninstall
description: setup node

# TODO input to verify

runs:
  using: composite
  steps:
    - name: node --version (before)
      shell: bash
      run: |
        which node
        node --version
      continue-on-error: true

    - name: rm node
      shell: bash
      run: |
        rm -rf /usr/local/bin/node

    # TODO?
    # Task pass, but exit 1 still shows
    # - name: node --version (after)
    #   shell: bash
    #   run: |
    #     which node
    #     node --version
    #   continue-on-error: true
