name: Verify
on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-reusable-workflows-node/.github/actions/node_setup@feat/workflows

      - uses: percebus/github-reusable-workflows/.github/actions/checkout@main

      - name: npm run setup
        run: npm run setup:ci --if-present

      - name: npm install
        run: npm ci
      - name: ls node_modules
        run: ls -la ./node_modules

      - name: npm run lint
        run: npm run lint
