name: Test actions/setup

on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup

  node__matrix:
    needs: default
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        node-version:
          - "" # LTS
          - "latest"
          - "22.0"
          - "23.0"

    name: node @ ${{ matrix.node-version }}
    steps:
      # - uses: ./.github/actions/setup  # FIXME Why doesn't this work?
      - uses: percebus/github-actions-node/.github/actions/setup@main # XXX
        with:
          node-version: ${{ matrix.node-version }}
